server:
  port: 8010
  http2:
    enabled: true
  servlet:
    context-path: /auth
  # undertow configuration
  undertow:
    accesslog:
      dir: logs
      enabled: false
      pattern: common
      prefix: auth_access
      suffix: log
    max-http-post-size: 10MB
    io-threads: 4
    worker-threads: 10
    buffer-size: 1024

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fin?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: admin123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: AUTH-POOL
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.mt.base.service.authentication.entity

jwt:
  header: Authorization
  secret: 8wm0Dc7EHJ1wR4XjT9ZmQfxuCMt839Qn60qptVSuzAF1rIQHjuGkSmvWbyPFuZBT
  # 24hour
  expiration: 86400000
  tokenHeader: 'Bearer '
  authorizeKey: auth
  # 服务器调用白名单，可填写IPV6地址
  whiteList: ['127.0.0.1', '0:0:0:0:0:0:0:1']
